export const FETCH_NOTIFICATION_REQUEST = 'FETCH_NOTIFICATION_REQUEST';
export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS';
export const FETCH_NOTIFICATION_FAILURE = 'FETCH_NOTIFICATION_FAILURE';
export const TOGGLE_NEW_WORKGROUP_MODAL = 'TOGGLE_NEW_WORKGROUP_MODAL';
export const CREATE_NEW_WORKGROUP_REQUEST = 'CREATE_NEW_WORKGROUP_REQUEST';
export const CREATE_NEW_WORKGROUP_SUCCESS = 'CREATE_NEW_WORKGROUP_SUCCESS';
export const CREATE_NEW_WORKGROUP_FAILURE = 'CREATE_NEW_WORKGROUP_FAILURE';
export const GET_ORGANIZATION_SELECTOR_DATA_REQUEST =
  'GET_ORGANIZATION_SELECTOR_DATA_REQUEST';
export const GET_ORGANIZATION_SELECTOR_DATA_SUCCESS =
  'GET_ORGANIZATION_SELECTOR_DATA_SUCCESS';
export const GET_ORGANIZATION_SELECTOR_DATA_FAILURE =
  'GET_ORGANIZATION_SELECTOR_DATA_FAILURE';
export const GET_WORKGROUPS_DATA_REQUEST = 'GET_WORKGROUPS_DATA_REQUEST';
export const GET_WORKGROUPS_DATA_SUCCESS = 'GET_WORKGROUPS_DATA_SUCCESS';
export const GET_WORKGROUPS_DATA_FAILURE = 'GET_WORKGROUPS_DATA_FAILURE';
export const GET_WORKGROUPS_SELECTED_DATA_REQUEST =
  'GET_WORKGROUPS_SELECTED_DATA_REQUEST';
export const GET_WORKGROUPS_SELECTED_DATA_SUCCESS =
  'GET_WORKGROUPS_SELECTED_DATA_SUCCESS';
export const GET_WORKGROUPS_SELECTED_DATA_FAILURE =
  'GET_WORKGROUPS_SELECTED_DATA_FAILURE';
export const SET_USER_WORKGROUPS_SELECTED = 'SET_USER_WORKGROUPS_SELECTED';
export const SET_CREATE_EDIT_WORKGROUP_IS_SUCCESSED =
  'SET_CREATE_EDIT_WORKGROUP_IS_SUCCESSED';
export const EDIT_WORKGROUP_REQUEST = 'EDIT_WORKGROUP_REQUEST';
export const EDIT_WORKGROUP_SUCCESS = 'EDIT_WORKGROUP_SUCCESS';
export const EDIT_WORKGROUP_FAILURE = 'EDIT_WORKGROUP_FAILURE';
export const SET_WORKGROUP_SELECT_RESPONSE_DATA =
  'SET_WORKGROUP_SELECT_RESPONSE_DATA';
export const DELETE_WORKGROUP_SUCCESS = 'DELETE_WORKGROUP_SUCCESS';
export const DELETE_WORKGROUP_FAILURE = 'DELETE_WORKGROUP_FAILURE';
export const RENAME_WORKGROUP_REQUEST = 'RENAME_WORKGROUP_REQUEST';
export const RENAME_WORKGROUP_SUCCESS = 'RENAME_WORKGROUP_SUCCESS';
export const RENAME_WORKGROUP_FAILURE = 'RENAME_WORKGROUP_FAILURE';
export const ADD_FAVORITES_FAILURE = 'ADD_FAVORITES_FAILURE';
export const UN_FAVORITE_FAILURE = 'UN_FAVORITE_FAILURE';
export const GET_FAVORITIES_SUCCESS = 'GET_FAVORITIES_SUCCESS';
export const GET_SEARCH_ORGANIZATION_DATA = 'GET_SEARCH_ORGANIZATION_DATA';
export const SET_SEARCH_SELECTED_ITEMS = 'SET_SEARCH_SELECTED_ITEMS';
export const GET_RECENT_TAB_ALL_DATA = 'GET_RECENT_TAB_ALL_DATA';
export const GLOBLE_SEARCH_DROPDOWN_VALUE = 'GLOBLE_SEARCH_DROPDOWN_VALUE';
