export const TOGGLE_CONTENT_SIDEBAR = 'TOGGLE_CONTENT_SIDEBAR';
export const TOGGLE_MENU = 'TOGGLE_CONTENT_SIDEBAR';
export const SET_SIDEBAR_CONTENT = 'SET_SIDEBAR_CONTENT';
export const ADD_TOAST_NOTIFICATION = 'ADD_TOAST_NOTIFICATION';
export const REMOVE_TOAST_NOTIFICATION = 'REMOVE_TOAST_NOTIFICATION';
export const PATIENT_SEARCH_REQUEST = 'PATIENT_SEARCH_REQUEST';
export const PATIENT_SEARCH_SUCCESS = 'PATIENT_SEARCH_SUCCESS';
export const PATIENT_SEARCH_FAILURE = 'PATIENT_SEARCH_FAILURE';
export const GET_LOOKUP_DROPDOWNS_DATA_REQUEST =
  'GET_LOOKUP_DROPDOWNS_DATA_REQUEST';
export const GET_LOOKUP_DROPDOWNS_DATA_SUCCESS =
  'GET_LOOKUP_DROPDOWNS_DATA_SUCCESS';
export const GET_LOOKUP_DROPDOWNS_DATA_FAILURE =
  'GET_LOOKUP_DROPDOWNS_DATA_FAILURE';
export const GET_ALL_GLOBLE_SEARCH_RECENTS_DATA_REQUEST =
  'GET_ALL_GLOBLE_SEARCH_RECENTS_DATA_REQUEST';
export const GET_ALL_GLOBLE_SEARCH_RECENTS_DATA_SUCCESS =
  'GET_ALL_GLOBLE_SEARCH_RECENTS_DATA_SUCCESS';
export const GET_ALL_GLOBLE_SEARCH_RECENTS_DATA_FAILURE =
  'GET_ALL_GLOBLE_SEARCH_RECENTS_DATA_FAILURE';
export const GET_PATIENT_INSURANCE_DATA_REQUEST =
  'GET_PATIENT_INSURANCE_DATA_REQUEST';
export const GET_PATIENT_INSURANCE_DATA_SUCCESS =
  'GET_PATIENT_INSURANCE_DATA_SUCCESS';
export const GET_PATIENT_INSURANCE_DATA_FAILURE =
  'GET_PATIENT_INSURANCE_DATA_FAILURE';
export const GET_CLAIM_PATIENT_INSURANCE_DATA_REQUEST =
  'GET_CLAIM_PATIENT_INSURANCE_DATA_REQUEST';
export const GET_CLAIM_PATIENT_INSURANCE_DATA_SUCCESS =
  'GET_CLAIM_PATIENT_INSURANCE_DATA_SUCCESS';
export const GET_CLAIM_PATIENT_INSURANCE_DATA_FAILURE =
  'GET_CLAIM_PATIENT_INSURANCE_DATA_FAILURE';
export const ASSIGN_CLAIM_TO_DATA_REQUEST = 'ASSIGN_CLAIM_TO_DATA_REQUEST';
export const ASSIGN_CLAIM_TO_DATA_SUCCESS = 'ASSIGN_CLAIM_TO_DATA_SUCCESS';
export const ASSIGN_CLAIM_TO_DATA_FAILURE = 'ASSIGN_CLAIM_TO_DATA_FAILURE';
export const REFERRING_PROVIDER_DATA_REQUEST =
  'REFERRING_PROVIDER_DATA_REQUEST';
export const REFERRING_PROVIDER_DATA_SUCCESS =
  'REFERRING_PROVIDER_DATA_SUCCESS';
export const REFERRING_PROVIDER_DATA_FAILURE =
  'REFERRING_PROVIDER_DATA_FAILURE';
export const GROUP_DATA_REQUEST = 'GROUP_DATA_REQUEST';
export const GROUP_DATA_SUCCESS = 'GROUP_DATA_SUCCESS';
export const GROUP_DATA_FAILURE = 'GROUP_DATA_FAILURE';
export const PRACTICE_DATA_REQUEST = 'PRACTICE_DATA_REQUEST';
export const PRACTICE_DATA_SUCCESS = 'PRACTICE_DATA_SUCCESS';
export const PRACTICE_DATA_FAILURE = 'PRACTICE_DATA_FAILURE';
export const FACILITY_DATA_REQUEST = 'FACILITY_DATA_REQUEST';
export const FACILITY_DATA_SUCCESS = 'FACILITY_DATA_SUCCESS';
export const FACILITY_DATA_FAILURE = 'FACILITY_DATA_FAILURE';
export const PROVIDER_DATA_REQUEST = 'PROVIDER_DATA_REQUEST';
export const PROVIDER_DATA_SUCCESS = 'PROVIDER_DATA_SUCCESS';
export const PROVIDER_DATA_FAILURE = 'PROVIDER_DATA_FAILURE';
export const SAVE_CLAIM_REQUEST = 'SAVE_CLAIM_REQUEST';
export const SAVE_CLAIM_SUCCESS = 'SAVE_CLAIM_SUCCESS';
export const SAVE_CLAIM_FAILURE = 'SAVE_CLAIM_FAILURE';
export const CPT_SEARCH_REQUEST = 'CPT_SEARCH_REQUEST';
export const CPT_SEARCH_SUCCESS = 'CPT_SEARCH_SUCCESS';
export const CPT_SEARCH_FAILURE = 'CPT_SEARCH_FAILURE';
export const SEARCH_PROVIDER_REQUEST = 'SEARCH_PROVIDER_REQUEST';
export const SEARCH_PROVIDER_SUCCESS = 'SEARCH_PROVIDER_SUCCESS';
export const SEARCH_PROVIDER_FAILURE = 'SEARCH_PROVIDER_FAILURE';
export const ICD_SEARCH_REQUEST = 'ICD_SEARCH_REQUEST';
export const ICD_SEARCH_SUCCESS = 'ICD_SEARCH_SUCCESS';
export const ICD_SEARCH_FAILURE = 'ICD_SEARCH_FAILURE';
export const BATCH_NUMBER_REQUEST = 'BATCH_NUMBER_REQUEST';
export const BATCH_NUMBER_SUCCESS = 'BATCH_NUMBER_SUCCESS';
export const BATCH_NUMBER_FAILURE = 'BATCH_NUMBER_FAILURE';
export const SAVE_CHARGE_REQUEST = 'SAVE_CHARGE_REQUEST';
export const SAVE_CHARGE_SUCCESS = 'SAVE_CHARGE_SUCCESS';
export const SAVE_CHARGE_FAILURE = 'SAVE_CHARGE_FAILURE';
export const EDIT_CLAIM_REQUEST = 'EDIT_CLAIM_REQUEST';
export const EDIT_CLAIM_SUCCESS = 'EDIT_CLAIM_SUCCESS';
export const EDIT_CLAIM_FAILURE = 'EDIT_CLAIM_FAILURE';
export const SET_APP_SPINNER = 'SET_APP_SPINNER';
export const CPT_NDC_REQUEST = 'CPT_NDC_REQUEST';
export const CPT_NDC_SUCCESS = 'CPT_NDC_SUCCESS';
export const CPT_NDC_FAILURE = 'CPT_NDC_FAILURE';
export const SAVE_CPT_NDC_REQUEST = 'SAVE_CPT_NDC_REQUEST';
export const SAVE_CPT_NDC_SUCCESS = 'SAVE_CPT_NDC_SUCCESS';
export const SAVE_CPT_NDC_FAILURE = 'SAVE_CPT_NDC_FAILURE';
export const BATCH_DOCUMENT_REQUEST = 'BATCH_DOCUMENT_REQUEST';
export const BATCH_DOCUMENT_SUCCESS = 'BATCH_DOCUMENT_SUCCESS';
export const BATCH_DOCUMENT_FAILURE = 'BATCH_DOCUMENT_FAILURE';
export const BATCH_DOCUMENT_PAGE_REQUEST = 'BATCH_DOCUMENT_PAGE_REQUEST';
export const BATCH_DOCUMENT_PAGE_SUCCESS = 'BATCH_DOCUMENT_PAGE_SUCCESS';
export const BATCH_DOCUMENT_PAGE_FAILURE = 'BATCH_DOCUMENT_PAGE_FAILURE';
export const UPDATE_CHARGE_REQUEST = 'UPDATE_CHARGE_REQUEST';
export const UPDATE_CHARGE_SUCCESS = 'UPDATE_CHARGE_SUCCESS';
export const UPDATE_CHARGE_FAILURE = 'UPDATE_CHARGE_FAILURE';
export const SET_ROUTE_HISTORY = 'SET_ROUTE_HISTORY';
export const SET_GLOBAL_MODAL = 'SET_GLOBAL_MODAL';
export const SET_SELECTED_PAYMENT_BATCHID = 'SET_SELECTED_PAYMENT_BATCHID';
export const SCRUB_CLAIM_REQUEST = 'SCRUB_CLAIM_REQUEST';
export const SCRUB_CLAIM_SUCCESS = 'SCRUB_CLAIM_SUCCESS';
export const SCRUB_CLAIM_FAILURE = 'SCRUB_CLAIM_FAILURE';
export const UPLOAD_DOCUMENT_REQUEST = 'UPLOAD_DOCUMENT_REQUEST';
export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS';
export const UPLOAD_DOCUMENT_FAILURE = 'UPLOAD_DOCUMENT_FAILURE';
export const FETCH_ALL_INSURANCE_DATA = 'FETCH_ALL_INSURANCE_DATA';
export const EXPAND_SIDEBAR_MENU = 'EXPAND_SIDEBAR_MENU';
export const SCREEN_INACTIVITY_STATUS = 'SCREEN_INACTIVITY_STATUS';
export const FETCH_AR_MANAGER_OPEN_AT_GLANCE_DATA =
  'FETCH_AR_MANAGER_OPEN_AT_GLANCE_DATA';
